export const ADDITEM  = 'ADDITEM';
export const DELETEITEM  = 'DELETEITEM';
export const EDITITEM  = 'EDITITEM';
export const OPENMODAL  = 'OPENMODAL';
export const HIDEMODAL  = 'HIDEMODAL';
export const UPDATESELECTCATEGORY  = 'UPDATESELECTCATEGORY';